### ISSUE TITLE
createdBy, modifiedBy 잘못된 값 입력되는 버그

### ISSUE THREAD

**Issue by pg-Parunson** [sparta-team6/CO-UP-TEAM-BE#163]
BaseEntity 클래스 에서 createdBy(UUID) , modifiedBy(UUID) 의 경우, 해당 액션을 취한 유저의 멤버ID(mbId)가 들어가야 하는 필드라고 생각하고 있습니다. (*또는 경우에 따라서 로그인 아이디logindId)

그런데 DB를 조회해보면 모든 테이블의 createdBy, modifiedBy 가 mbId도 아니고 loginId도 아닌 의문의 난수값이 들어가 있습니다.

이 문제에 대해 인지하고 계신 내용이 있으시면 공유 부탁 드립니다.

**Comment by Hong-Seungmin** [comment]
UUID타입에 대해서 JPA는 기본적으로 binary로 처리하고 있습니다. 일단 db에 들어있는 값은 binary값이라 자연스럽게 읽지는 못하고,
다시 뽑아낸다면 아마 UUID가 정상적으로 들어갈 것입니다.

이런 구조가 싫다면 entity에서 컬럼생성타입을 지정해주면 될것 같고,
타입을 지정하게 된다면, db테이블에 데이터가 없어야 db를 사용할 수 있을것으로 예상됩니다.
